/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type OgImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "ogImage.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type HeaderImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "headerImage.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Uses = {
  _id: string;
  _type: "uses";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  categories?: Array<{
    title?: string;
    items?: Array<{
      name?: string;
      description?: string;
      url?: string;
      _type: "usesItem";
      _key: string;
    }>;
    _type: "usesCategory";
    _key: string;
  }>;
};

export type Now = {
  _id: string;
  _type: "now";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  publishedAt?: string;
  body?: BlockContent;
  media?: Array<{
    label?: string;
    value?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "mediaRow";
    _key: string;
  }>;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  body?: BlockContent;
};

export type Appearance = {
  _id: string;
  _type: "appearance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  appearanceType?: "podcast" | "video" | "livestream" | "talk" | "presentation";
  externalUrl?: string;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  projectUrl?: string;
  githubUrl?: string;
  company?: CompanyReference;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & Callout)
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Callout = {
  _type: "callout";
  variant?: "info" | "tip" | "important" | "warning" | "caution";
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | OgImage
  | HeaderImage
  | Uses
  | Now
  | About
  | Appearance
  | CompanyReference
  | Project
  | Company
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Post
  | BlockContent
  | Callout
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt, "company": company->{name, "slug": slug.current}}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  company: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: APPEARANCES_QUERY
// Query: *[_type == "appearance" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}
export type APPEARANCES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LATEST_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}
export type LATEST_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LATEST_APPEARANCES_QUERY
// Query: *[_type == "appearance" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}
export type LATEST_APPEARANCES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LINKS_LATEST_QUERY
// Query: {  "post": *[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage},  "project": *[_type == "project" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage},  "appearance": *[_type == "appearance" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage}}
export type LINKS_LATEST_QUERY_RESULT = {
  post: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    ogImage: OgImage | null;
  } | null;
  project: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    ogImage: OgImage | null;
  } | null;
  appearance: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    ogImage: OgImage | null;
  } | null;
};

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]
export type POST_QUERY_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    ...,    "company": company->{name, "slug": slug.current}  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  projectUrl?: string;
  githubUrl?: string;
  company: {
    name: string | null;
    slug: string | null;
  } | null;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: APPEARANCE_QUERY
// Query: *[_type == "appearance" && slug.current == $slug][0]
export type APPEARANCE_QUERY_RESULT = {
  _id: string;
  _type: "appearance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  appearanceType?: "livestream" | "podcast" | "presentation" | "talk" | "video";
  externalUrl?: string;
  description?: string;
  ogImage?: OgImage;
  headerImage?: HeaderImage;
  body?: BlockContent;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{"params": {"slug": slug.current}}
export type POST_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{"params": {"slug": slug.current}}
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: APPEARANCE_SLUGS_QUERY
// Query: *[_type == "appearance" && defined(slug.current)]{"params": {"slug": slug.current}}
export type APPEARANCE_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0]{title, description, body}
export type ABOUT_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  body: BlockContent | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: USES_QUERY
// Query: *[_type == "uses"][0]{title, description, categories[]{title, items[]{name, description, url}}}
export type USES_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  categories: Array<{
    title: string | null;
    items: Array<{
      name: string | null;
      description: string | null;
      url: string | null;
    }> | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NOW_QUERY
// Query: *[_type == "now"]|order(publishedAt desc){_id, publishedAt, body, media}
export type NOW_QUERY_RESULT = Array<{
  _id: string;
  publishedAt: string | null;
  body: BlockContent | null;
  media: Array<{
    label?: string;
    value?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "mediaRow";
    _key: string;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_HUBS_QUERY
// Query: {  "companies": *[_type == "company" && defined(slug.current)]|order(name asc){    name,    "slug": slug.current,    url,    logo,    description,    "projects": *[_type == "project" && references(^._id) && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}  },  "personal": *[_type == "project" && !defined(company) && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}}
export type WORK_HUBS_QUERY_RESULT = {
  companies: Array<{
    name: string | null;
    slug: string | null;
    url: string | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    description: string | null;
    projects: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
      publishedAt: string | null;
    }>;
  }>;
  personal: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}': POSTS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt, "company": company->{name, "slug": slug.current}}': PROJECTS_QUERY_RESULT;
    '*[_type == "appearance" && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}': APPEARANCES_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}': LATEST_POSTS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}': LATEST_PROJECTS_QUERY_RESULT;
    '*[_type == "appearance" && defined(slug.current)]|order(publishedAt desc)[0...3]{_id, title, slug, publishedAt}': LATEST_APPEARANCES_QUERY_RESULT;
    '{\n  "post": *[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage},\n  "project": *[_type == "project" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage},\n  "appearance": *[_type == "appearance" && defined(slug.current)]|order(publishedAt desc)[0]{_id, title, slug, ogImage}\n}': LINKS_LATEST_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]': POST_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n    ...,\n    "company": company->{name, "slug": slug.current}\n  }': PROJECT_QUERY_RESULT;
    '*[_type == "appearance" && slug.current == $slug][0]': APPEARANCE_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{"params": {"slug": slug.current}}': POST_SLUGS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]{"params": {"slug": slug.current}}': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "appearance" && defined(slug.current)]{"params": {"slug": slug.current}}': APPEARANCE_SLUGS_QUERY_RESULT;
    '*[_type == "about"][0]{title, description, body}': ABOUT_QUERY_RESULT;
    '*[_type == "uses"][0]{title, description, categories[]{title, items[]{name, description, url}}}': USES_QUERY_RESULT;
    '*[_type == "now"]|order(publishedAt desc){_id, publishedAt, body, media}': NOW_QUERY_RESULT;
    '{\n  "companies": *[_type == "company" && defined(slug.current)]|order(name asc){\n    name,\n    "slug": slug.current,\n    url,\n    logo,\n    description,\n    "projects": *[_type == "project" && references(^._id) && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}\n  },\n  "personal": *[_type == "project" && !defined(company) && defined(slug.current)]|order(publishedAt desc){_id, title, slug, publishedAt}\n}': WORK_HUBS_QUERY_RESULT;
  }
}
